GROQ_API_KEY = "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"
HF_API_KEY = "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"
LANGCHAIN_TRACING_V2='true'
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="ls__6af86d84933a485181eab6b66ecd14d0"
LANGCHAIN_PROJECT="ChatGroq"